schema: aws-role/v1
name: "nwarila-platform_secure-wazuh_reaper"
session_seconds: 3600
trust: "nwarila-platform_secure-wazuh_reaper.trust.json"
attach:
  - "nwarila-platform_secure-wazuh_reaper_ebs"
  - "nwarila-platform_secure-wazuh_reaper_ec2"
  - "nwarila-platform_secure-wazuh_reaper_eni"
  - "nwarila-platform_secure-wazuh_reaper_iam"
  - "nwarila-platform_secure-wazuh_reaper_s3"
  - "nwarila-platform_secure-wazuh_reaper_sg"
managed_attach: []
path: /
description: null
managed_by: consumer
